# Default cloudbuild.yaml for Cloud Shell custom images.
# This file is used by the Cloud Build trigger that builds this image.

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/button', '.']
- name: 'gcr.io/cloudshell-images/custom-image-validation'
  args: ['image_test.py', '--image', 'gcr.io/$PROJECT_ID/button']
images: ['gcr.io/$PROJECT_ID/button']
timeout: '1200s'
